# Generated by Django 4.2 on 2023-10-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
