# Generated by Django 4.2 on 2023-11-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_lead_date_added_lead_description_lead_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.IntegerField(default=0, verbose_name='client Age'),
        ),
    ]
