# Generated by Django 4.2 on 2023-11-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_alter_lead_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='social_media_accounts',
            field=models.CharField(blank=True, choices=[('Youtube', 'Youtube'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Reddit', 'Reddit'), ('Discord', 'Discord'), ('Github', 'Github'), ('LinkedIn', 'LinkedIn'), ('Tik Tok', 'Tik Tok'), ('Others', 'Others'), ('Snapchat', 'Snapchat')], max_length=20, null=True),
        ),
    ]
