# Generated by Django 4.2 on 2023-11-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_agent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='slug',
            field=models.SlugField(default='into-the-deep-blue'),
            preserve_default=False,
        ),
    ]
