# Generated by Django 4.2 on 2023-11-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_lead_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='category-slugify'),
            preserve_default=False,
        ),
    ]
