# Generated by Django 4.2 on 2023-11-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
