# Generated by Django 4.2 on 2023-11-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_alter_lead_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='slug',
            field=models.SlugField(default='fgyhjhgfds'),
            preserve_default=False,
        ),
    ]
