# Generated by Django 4.2 on 2023-11-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_ticket',
            field=models.CharField(default='8765432fds', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
