# Generated by Django 4.2 on 2023-12-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_alter_lead_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['id', 'phone_number']},
        ),
    ]
