# Generated by Django 4.2 on 2023-12-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_alter_agent_email_alter_lead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Input your Email', max_length=254, unique=True),
        ),
    ]
