# Generated by Django 4.2 on 2023-12-11 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0031_alter_lead_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('slug', models.SlugField()),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=15)),
                ('sign_in_time', models.CharField(help_text='Enter the time you resumed for work in this format -> 8:00am', max_length=8)),
                ('sign_out_time', models.CharField(help_text='Enter the time you closed for work in this format -> 8:00pm', max_length=8)),
                ('date_added', models.CharField(help_text='Enter the date you resumed for work in this format -> 12/12/2023', max_length=10)),
                ('staff_attendance_ref', models.CharField(blank=True, max_length=15, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.management', verbose_name='Management')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'ordering': ['id', 'date_created'],
            },
        ),
    ]
