# Generated by Django 4.2 on 2023-12-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_attendance_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='branch',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sign_in_time',
            field=models.CharField(help_text='Enter the time you resumed for work in this format -> 8:00 am', max_length=8),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sign_out_time',
            field=models.CharField(help_text='Enter the time you closed for work in this format -> 8:00 pm', max_length=8),
        ),
    ]
