# Generated by Django 4.2 on 2023-12-11 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_alter_lead_options'),
        ('staff', '0003_remove_attendance_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='management',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Branch'),
        ),
    ]
