# Generated by Django 4.2 on 2023-12-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_attendance_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='staff_attendance_ref',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Staff Daily Attendance Ref '),
        ),
    ]
