# Generated by Django 4.2 on 2023-12-12 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_attendance_staff_attendance_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='phone_number',
            field=models.CharField(default='08165432234', max_length=12, validators=[django.core.validators.MinValueValidator('0101000000'), django.core.validators.MaxValueValidator('+234-010100000')]),
            preserve_default=False,
        ),
    ]
