# Generated by Django 4.2 on 2023-12-12 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_management_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinValueValidator('0101000000'), django.core.validators.MaxValueValidator('+111-01010000')]),
        ),
    ]
