# Generated by Django 4.2 on 2023-12-12 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_management_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinValueValidator('010100000'), django.core.validators.MaxValueValidator('099010100000')]),
        ),
    ]
