# Generated by Django 4.2 on 2023-12-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_management_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='full_name',
            field=models.CharField(max_length=30),
        ),
    ]
