# Generated by Django 4.2 on 2023-12-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_attendance_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sign_out_time',
            field=models.CharField(blank=True, help_text='Enter the time you closed for work in this format -> 8:00 pm', max_length=8, null=True),
        ),
    ]
