# Generated by Django 4.2 on 2023-12-15 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_attendance_sign_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sign_in_time',
            field=models.CharField(help_text='Enter the time you resumed for work in this format -> 8:00', max_length=4, validators=[django.core.validators.MinValueValidator('0:00'), django.core.validators.MaxValueValidator('24:00')]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sign_out_time',
            field=models.CharField(blank=True, help_text='Enter the time you closed for work in this format -> 8:00 pm. Make sure you             update this field and fill in the option before you leave your workplace, not now please.', max_length=4, null=True, validators=[django.core.validators.MinValueValidator('0:00'), django.core.validators.MaxValueValidator('24:00')]),
        ),
    ]
