# Generated by Django 4.2 on 2023-12-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_attendance_sign_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sign_in_time',
            field=models.CharField(help_text='Enter the time you resumed for work in this format -> 8:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sign_out_time',
            field=models.CharField(blank=True, help_text='Enter the time you closed for work in this format -> 8:00. Make sure you             update this field and fill in the option before you leave your workplace, not now please.', max_length=5, null=True),
        ),
    ]
