# Generated by Django 4.2 on 2023-12-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_attendance_sign_in_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['id'], 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='date_sign_out_time',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
