# Generated by Django 4.2 on 2023-12-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
