# Generated by Django 4.2 on 2023-12-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_alter_attendance_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sign_out_time',
            field=models.CharField(blank=True, help_text='Enter the time you closed for work in this format ->            8:00. Make sure you update this field and fill in the option                 before you leave your workplace, not now please.', max_length=5, null=True),
        ),
    ]
