# Generated by Django 4.2 on 2023-12-28 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0035_alter_managementprofile_user_and_more'),
        ('staff', '0017_alter_attendance_sign_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.managementprofile'),
            preserve_default=False,
        ),
    ]
