# Generated by Django 4.2 on 2023-12-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_alter_attendance_full_name_alter_attendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.management', verbose_name='Management'),
        ),
    ]
