# Generated by Django 4.2 on 2023-12-29 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_alter_attendance_sign_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1\\d{9,12}$')]),
        ),
    ]
