# Generated by Django 4.2 on 2023-12-30 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_alter_management_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sign_in_time',
            field=models.CharField(help_text='Enter the time you resumed for work in this format -> 8:00', max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a         valid value that consist of number from 0-9 with a colon (:) in between the two numbers.', regex='[0-9]+:[0-9]+(?![^()]*\\\\)')]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sign_out_time',
            field=models.CharField(blank=True, help_text='Enter the time you closed for work in this format ->            8:00. Make sure you update this field and fill in the option                 before you leave your workplace, not now please.', max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Enter a         valid value that consist of number from 0-9 with a colon (:) in between the two numbers.', regex='[0-9]+:[0-9]+(?![^()]*\\\\)')]),
        ),
    ]
