# Generated by Django 4.2 on 2024-01-05 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_alter_attendance_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_added',
            field=models.CharField(help_text='Enter the date you resumed for work in            this format -> 12/12/2023', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a         valid value that consist of number and a slash in standard date time format eg. 1/5/2024 (D/M/Y).', regex='^(0?[1-9]|1[0-2])\\/(0?[1-9]|[12][0-9]|3[01])\\/(19|20)\\d{2}$')]),
        ),
    ]
