# Generated by Django 4.2 on 2024-01-07 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_alter_attendance_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='expected_sign_in_time',
            field=models.CharField(default='9:00', help_text='Enter the time you resumed for work in this format -> 8:00', max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a         valid value that consist of number from 0-9 with a colon             (:) in between the two numbers.', regex='[0-9]+:[0-9]+(?![^()]*\\\\)')]),
            preserve_default=False,
        ),
    ]
