# Generated by Django 4.2 on 2023-11-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_rename_subscribe_subscribedusers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pharmacist',
            field=models.BooleanField(default=False),
        ),
    ]
