# Generated by Django 4.2 on 2023-11-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_user_is_pharmacist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='is an agent?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=True, verbose_name='is an organizer?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_pharmacist',
            field=models.BooleanField(default=False, verbose_name='is pharmacist?'),
        ),
    ]
