# Generated by Django 4.2 on 2023-12-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_alter_user_is_agent_alter_user_is_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_management',
            field=models.BooleanField(default=False, verbose_name='is management?'),
        ),
    ]
