# Generated by Django 4.2 on 2023-12-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_user_is_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_management',
            field=models.BooleanField(default=False, verbose_name='is the management?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_pharmacist',
            field=models.BooleanField(default=False, verbose_name=' a pharmacist?'),
        ),
    ]
