# Generated by Django 4.2 on 2023-12-12 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_alter_user_is_management_alter_user_is_pharmacist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='08134567898', max_length=15, validators=[django.core.validators.MinValueValidator('0101000000'), django.core.validators.MaxValueValidator('+111-010-10000')]),
            preserve_default=False,
        ),
    ]
