# Generated by Django 4.2 on 2023-12-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=False, verbose_name='is an organizer?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_pharmacist',
            field=models.BooleanField(default=False, verbose_name=' is a pharmacist?'),
        ),
    ]
