# Generated by Django 4.2 on 2023-12-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=True, verbose_name='is an organizer?'),
        ),
    ]
