# Generated by Django 4.2 on 2023-11-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_alter_lead_agent'),
        ('pharmcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdetail',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='patientdetail',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
    ]
