# Generated by Django 4.2 on 2023-11-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0002_alter_patientdetail_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetail',
            old_name='agent',
            new_name='pharmacist',
        ),
    ]
