# Generated by Django 4.2 on 2023-11-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0003_rename_agent_patientdetail_pharmacist'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
