# Generated by Django 4.2 on 2023-11-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0004_patientdetail_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='pharm_care_fee',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
