# Generated by Django 4.2 on 2023-11-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0005_patientdetail_pharm_care_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
