# Generated by Django 4.2 on 2023-11-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0006_patientdetail_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetail',
            old_name='pharm_care_fee',
            new_name='consultation',
        ),
    ]
