# Generated by Django 4.2 on 2023-11-22 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0007_rename_pharm_care_fee_patientdetail_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmcare.medicationhistory'),
            preserve_default=False,
        ),
    ]
