# Generated by Django 4.2 on 2023-11-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0010_alter_medicationhistory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisofclinicalproblem',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupplan',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationchanges',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoringplan',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
