# Generated by Django 4.2 on 2023-11-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0011_alter_analysisofclinicalproblem_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressnote',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
