# Generated by Django 4.2 on 2023-11-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0013_alter_monitoringplan_has_improved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_details',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AlterField(
            model_name='patient',
            name='total',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Total (auto-add)'),
        ),
    ]
