# Generated by Django 4.2 on 2023-11-24 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_alter_contact_full_name_alter_contact_subject'),
        ('pharmcare', '0014_rename_patient_details_patient_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent', verbose_name='Pharmacist'),
        ),
    ]
