# Generated by Django 4.2 on 2023-11-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0015_patient_pharmacist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationchanges',
            options={'ordering': ['id'], 'verbose_name_plural': 'Medication Changes'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='monitoringplan',
            name='has_improved',
        ),
        migrations.AddField(
            model_name='pharmaceuticalcareplan',
            name='has_improved',
            field=models.BooleanField(default=False, verbose_name="has improved (tick good, if yes, otherwise don't.)"),
        ),
    ]
