# Generated by Django 4.2 on 2023-11-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0017_alter_medicationchanges_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationchanges',
            name='start_or_continued_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Start/Continued Date'),
        ),
    ]
