# Generated by Django 4.2 on 2023-11-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0018_alter_medicationchanges_start_or_continued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationchanges',
            name='start_or_continued_date',
            field=models.CharField(default='12/3/2023', max_length=50, verbose_name='Start/Continued Date'),
            preserve_default=False,
        ),
    ]
