# Generated by Django 4.2 on 2023-11-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0019_alter_medicationchanges_start_or_continued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='weight',
            field=models.PositiveBigIntegerField(blank=True, error_messages="Kindly provide the patient's weight", null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='height',
            field=models.PositiveBigIntegerField(blank=True, error_messages="Kindly provide the patient's ", null=True),
        ),
    ]
