# Generated by Django 4.2 on 2023-11-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0020_patientdetail_weight_alter_patientdetail_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='height',
            field=models.IntegerField(blank=True, default=1, error_messages="Kindly provide the patient's", help_text='must be provided in ft', null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='weight',
            field=models.IntegerField(blank=True, default=1, error_messages="Kindly provide the patient's weight", help_text='must be provided in kg', null=True),
        ),
    ]
