# Generated by Django 4.2 on 2023-11-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0021_alter_patientdetail_email_alter_patientdetail_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='weight',
            field=models.IntegerField(blank=True, error_messages="Kindly provide the patient's weight", help_text='must be provided in kg', null=True),
        ),
    ]
