# Generated by Django 4.2 on 2023-12-02 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0022_alter_patientdetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medication_changes',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmcare.medicationchanges'),
            preserve_default=False,
        ),
    ]
