# Generated by Django 4.2 on 2023-12-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_alter_contact_full_name_alter_contact_subject'),
        ('pharmcare', '0022_alter_patientdetail_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdetail',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='pharmaceuticalcareplan',
            name='pharmacist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.agent', verbose_name='Pharmacist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='height',
            field=models.IntegerField(blank=True, error_messages="Kindly provide the patient's", help_text='must be provided in ft', null=True),
        ),
    ]
