# Generated by Django 4.2 on 2023-12-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0023_patient_medication_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medication_changes',
        ),
    ]
