# Generated by Django 4.2 on 2023-12-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0024_remove_patient_medication_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisofclinicalproblem',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicationchanges',
            name='medication_list',
            field=models.CharField(max_length=100),
        ),
    ]
