# Generated by Django 4.2 on 2023-12-03 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0026_alter_followupplan_slug_alter_medicationchanges_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupplan',
            name='user',
        ),
        migrations.AddField(
            model_name='followupplan',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmcare.patientdetail'),
        ),
        migrations.AlterField(
            model_name='followupplan',
            name='state_of_improvement_by_score',
            field=models.CharField(default='eg -> 70%', max_length=4),
        ),
    ]
