# Generated by Django 4.2 on 2023-12-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0027_remove_followupplan_user_followupplan_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Fullname')),
                ('position', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=200)),
                ('alt_description', models.CharField(max_length=60)),
                ('facebook_aria_label', models.CharField(max_length=30)),
                ('twitter_aria_label', models.CharField(max_length=30)),
                ('instagram_aria_label', models.CharField(max_length=30)),
                ('facebook_link', models.CharField(max_length=150, unique=True)),
                ('instagram_link', models.CharField(max_length=150, unique=True)),
                ('twitter_link', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='followupplan',
            name='state_of_improvement_by_score',
            field=models.CharField(default='for example -> 70%', max_length=4),
        ),
    ]
