# Generated by Django 4.2 on 2023-12-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0029_alter_team_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='chat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
