# Generated by Django 4.2 on 2023-12-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0030_team_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Med-Connect Staff'},
        ),
    ]
