# Generated by Django 4.2 on 2023-12-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0031_alter_team_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmaceuticalcareplan',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2023-12-06 08:20:49.206533'),
            preserve_default=False,
        ),
    ]
