# Generated by Django 4.2 on 2023-12-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0032_pharmaceuticalcareplan_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmaceuticalcareplan',
            name='patient_full_name',
            field=models.CharField(default='Onyekwelu Kenny', max_length=20),
            preserve_default=False,
        ),
    ]
