# Generated by Django 4.2 on 2023-12-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0035_pharmaceuticalcareplan_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmaceuticalcareplan',
            old_name='amount',
            new_name='total_payment',
        ),
        migrations.AddField(
            model_name='pharmaceuticalcareplan',
            name='discount',
            field=models.PositiveBigIntegerField(blank=True, help_text='discount given to patient, perhaps due to his/her consistent loyalty, if any.', null=True),
        ),
    ]
