# Generated by Django 4.2 on 2023-12-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0036_rename_amount_pharmaceuticalcareplan_total_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaceuticalcareplan',
            name='total_payment',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
