# Generated by Django 4.2 on 2023-12-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0041_alter_pharmaceuticalcareplan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaceuticalcareplan',
            name='discount',
            field=models.PositiveBigIntegerField(blank=True, help_text='discount given to patient,            perhaps due to his/her consistent loyalty, if any.', null=True),
        ),
    ]
