# Generated by Django 4.2 on 2023-12-16 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_alter_lead_options'),
        ('pharmcare', '0043_alter_patientdetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
