# Generated by Django 4.2 on 2023-12-16 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_alter_lead_options'),
        ('pharmcare', '0044_alter_patientdetail_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
    ]
