# Generated by Django 4.2 on 2023-12-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0046_alter_patientdetail_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='height',
            field=models.FloatField(blank=True, error_messages="Kindly provide the patient's", help_text='must be provided in ft', null=True),
        ),
    ]
