# Generated by Django 4.2 on 2023-12-17 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmcare', '0048_patient_slug_alter_pharmaceuticalcareplan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='leads',
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
