# Generated by Django 4.2 on 2023-12-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0049_remove_patient_leads_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='slug',
            field=models.SlugField(default='werftuhjikuy7654'),
            preserve_default=False,
        ),
    ]
