# Generated by Django 4.2 on 2023-12-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0051_alter_patient_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='slug',
        ),
    ]
