# Generated by Django 4.2 on 2023-12-17 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0052_remove_patient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmcare.medicationhistory'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmcare.patientdetail', verbose_name='Patient-detail'),
        ),
    ]
