# Generated by Django 4.2 on 2023-12-17 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0053_alter_patient_medical_history_alter_patient_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmcare.medicationhistory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmcare.patientdetail', verbose_name='Patient-detail'),
            preserve_default=False,
        ),
    ]
