# Generated by Django 4.2 on 2023-12-17 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_alter_lead_options'),
        ('pharmcare', '0055_patient_organization_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmaceuticalcareplan',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
    ]
