# Generated by Django 4.2 on 2023-12-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0056_pharmaceuticalcareplan_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
