# Generated by Django 4.2 on 2023-12-20 01:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0033_alter_contact_email'),
        ('pharmcare', '0057_alter_patientdetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmaceuticalcareplan',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.MinValueValidator('010100000'), django.core.validators.MaxValueValidator('099010100000')])),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('slug', models.SlugField()),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile', verbose_name='Branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='pharmacist',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmcare.pharmacist', verbose_name='Pharmacist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='pharmacist',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmcare.pharmacist', verbose_name='Pharmacist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmaceuticalcareplan',
            name='pharmacist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmcare.pharmacist'),
            preserve_default=False,
        ),
    ]
