# Generated by Django 4.2 on 2023-12-21 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0058_alter_patientdetail_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pharmacist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmcare.pharmacist', verbose_name='Pharmacist'),
        ),
    ]
