# Generated by Django 4.2 on 2023-12-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0059_alter_patient_pharmacist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
