# Generated by Django 4.2 on 2023-12-21 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0060_alter_patientdetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmcare.pharmacist', verbose_name='Pharmacist'),
        ),
    ]
