# Generated by Django 4.2 on 2023-12-21 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_alter_contact_email'),
        ('pharmcare', '0061_alter_patientdetail_pharmacist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pharmacist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmcare.pharmacist'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
