# Generated by Django 4.2 on 2023-12-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0062_alter_patient_pharmacist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='weight',
            field=models.FloatField(blank=True, error_messages="Kindly provide the patient's weight", help_text='must be provided in kg', null=True),
        ),
    ]
