# Generated by Django 4.2 on 2023-12-22 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0063_alter_patientdetail_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
