# Generated by Django 4.2 on 2023-12-22 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0064_alter_patientdetail_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinValueValidator('010100000'), django.core.validators.MaxValueValidator('099910000')]),
        ),
    ]
