# Generated by Django 4.2 on 2023-12-22 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0065_alter_patientdetail_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinValueValidator('01010000000'), django.core.validators.MaxValueValidator('09991000000')]),
        ),
    ]
