# Generated by Django 4.2 on 2023-12-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0071_alter_patient_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmcare.medicationhistory'),
        ),
    ]
