# Generated by Django 4.2 on 2023-12-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_alter_contact_email'),
        ('pharmcare', '0073_analysisofclinicalproblem_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringplan',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoringplan',
            name='pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmcare.pharmacist'),
        ),
    ]
