# Generated by Django 4.2 on 2023-12-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0074_monitoringplan_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringplan',
            name='frequency',
            field=models.CharField(max_length=100, verbose_name='Result(s) and Action Plan'),
        ),
    ]
