# Generated by Django 4.2 on 2023-12-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0075_alter_monitoringplan_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdetail',
            options={'ordering': ['id', 'first_name']},
        ),
        migrations.AddField(
            model_name='patient',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
