# Generated by Django 4.2 on 2023-12-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0076_alter_patientdetail_options_patient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaceuticalcareplan',
            name='discount',
            field=models.PositiveBigIntegerField(blank=True, default=0, help_text='discount given to patient,            perhaps due to his/her consistent loyalty, if any.', null=True),
        ),
    ]
