# Generated by Django 4.2 on 2023-12-28 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0077_alter_pharmaceuticalcareplan_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalcareplan',
            name='has_improved',
            field=models.BooleanField(default=False, verbose_name="has improved                                     (tick good, if yes, otherwise don't.)"),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1\\d{9,12}$')]),
        ),
    ]
