# Generated by Django 4.2 on 2023-12-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0078_alter_patientdetail_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisofclinicalproblem',
            options={'ordering': ['id', '-date_created'], 'verbose_name_plural': 'Analysis of Clinical Problems'},
        ),
        migrations.AlterModelOptions(
            name='followupplan',
            options={'ordering': ['id', '-date_created']},
        ),
        migrations.AlterModelOptions(
            name='medicationchanges',
            options={'ordering': ['id', '-date_created'], 'verbose_name_plural': 'Medication Changes'},
        ),
        migrations.AlterModelOptions(
            name='medicationhistory',
            options={'ordering': ['id', '-date_created'], 'verbose_name_plural': 'Medication History'},
        ),
        migrations.AlterModelOptions(
            name='monitoringplan',
            options={'ordering': ['id', '-date_created']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id', '-date_created']},
        ),
        migrations.AlterModelOptions(
            name='patientdetail',
            options={'ordering': ['id', '-date_created']},
        ),
        migrations.AlterModelOptions(
            name='pharmaceuticalcareplan',
            options={'ordering': ['id', '-date_created']},
        ),
        migrations.AlterModelOptions(
            name='progressnote',
            options={'ordering': ['id', '-date_created']},
        ),
    ]
