# Generated by Django 4.2 on 2023-12-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0079_alter_analysisofclinicalproblem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaceuticalcareplan',
            name='discount',
            field=models.PositiveBigIntegerField(blank=True, help_text='discount given to patient,            perhaps due to his/her consistent loyalty, if any.', null=True),
        ),
    ]
