# Generated by Django 4.2 on 2023-12-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0080_alter_pharmaceuticalcareplan_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmaceuticalcareplan',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
