# Generated by Django 4.2 on 2024-01-01 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0081_pharmaceuticalcareplan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupplan',
            name='state_of_improvement_by_score',
            field=models.CharField(default='for example -> 70%', max_length=3, validators=[django.core.validators.RegexValidator(regex='^[0-9%]+$')]),
        ),
    ]
