# Generated by Django 4.2 on 2024-01-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcare', '0083_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaceuticalcareplan',
            name='discount',
            field=models.PositiveBigIntegerField(blank=True, help_text='discount given to patient,            perhaps due to his/her consistent loyalty strictly authorized by                 management (if any).', null=True),
        ),
    ]
